### ISSUE TITLE
What features are missing to run checker.ts?

### ISSUE THREAD

**Issue by danvk** [marcj/TypeRunner#15]
I've been reading through [Part 3](https://craftinginterpreters.com/a-bytecode-virtual-machine.html) of _Crafting Interpreters_ and find the idea of a custom bytecode/VM designed for TypeScript to be pretty exciting!

One idea for making this a drop-in replacement for `tsc` would be to add just enough features so that it could compile and run `checker.ts`, `binder.ts`, etc. from the TypeScript repo. This might be more tractable than supporting all of TypeScript since you'd only need to support the features that are used by the TypeScript compiler itself. Performance might not be as good as your pure C++ compiler, but it would have feature parity with `tsc` and might still be faster than running it through Node.js. So I'm curious how close this is to being able to run `checker.ts`.

Or maybe I'm misunderstanding this project!

**Comment by marcj** [comment]
I'm afraid there is a misunderstanding: TypeRunner runs TypeScript in an abstract level, in type world. It doesn't actually execute JavaScript as v8 for example would. So, it is not possible to run `checker.ts` or any other file, as that was never the goal. The goal was to execute JavaScript on a higher level that allows to reason about the potential type representation in memory as if the JS was actually executed plus run the type system. The same thing that tsc does, but much closer to hardware.

I think the idea of the project is still tractable, it would just need many months of work until we have a version and probably 1 year until we have something that can be used by many people already. It's more about "why would someone invest 1 year full-time into this" since return of invest is a bit unclear.

**Comment by danvk** [comment]
Gotcha, thanks for the clarification!
