### ISSUE TITLE
Drop TS

### ISSUE THREAD

**Issue by hinell** [marcj/TypeRunner#5]
## Drop TypeScript
>_Since the TypeScript team doesn't have unlimited resources this means however that they have to focus on what brings growth. <sup>[readme.md]</sup>_

I think it's better to drop TS altogether cause it's moving in a completely wrong direction.
1. Wrong priorities. The last few years the team was busy introducing quite weird hacking around strings that I strongly disagree with and that basically reject OOP concept. There hundreds of issues that the team didn't focus on. Meanwhile, there are thousands of issues that were opened for years now.
2. Growing syntax complexity that breaks backwards-compatibility. Like take a look at this [ECMA Import syntax introduced by TS v4.7](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#resolution-mode):
```typescript
// A total mess
import type { TypeFromRequire } from "pkg" assert {
    "resolution-mode": "require"
};
```
4. It doesn't provide good typechecking anymore. TypeScript doesn't improve performance and typechecking suffers from serious performance drops in huge projects (this has been improved by `incremental` option though)
5. Sometimes it introduces completely unjustified productivity issues that may stall entire project.

## We need a better language
I think the community and industry should adopt a new type-safe language. It would be best to have tooling that would allow one to migrate from TS to a new codebase smoothing out corners during  transition process.

**Comment by marcj** [comment]
I think you underestimate the power of a language that is highly adopted. It doesn't have to be perfect to create value. Dropping TS support is no-no for me

**Comment by richardwillars** [comment]
Just to add a thought on this one. If the aim of the project is to cover a stricter version of TypeScript, you have essentially forked it, but kept the same name. The problem will come when a developer uses an npm module, and has no idea if it's going to work with TypeRunner - the npm library is written in TypeScript but you don't know what parts of the language it's using, so could easily crash on compile.

My personal view is that the logical approach is to do as @hinell suggested and create a new type-safe language. It could still be TypeScript syntax etc and follow all the principles you're planning to, but it would need a new name so that developers could say their packages are 'XXX' and 'TypeScript' compatible.
